"""Unit tests exercising BM25 search against pre-built CI fixture databases.

These tests load the checked-in SQLite segment .db files and verify
search results match the golden expectations. The golden files are
generated by scripts/build_test_fixtures.py.
"""

import json
from pathlib import Path

import pytest

from docs_mcp_server.search.bm25_engine import BM25SearchEngine
from docs_mcp_server.search.sqlite_storage import SqliteSegmentStore


FIXTURE_DIR = Path(__file__).parent.parent / "fixtures" / "ci_mcp_data"
GOLDEN_DIR = Path(__file__).parent.parent / "fixtures" / "golden"

pytestmark = pytest.mark.unit


def _load_golden(filename: str) -> dict:
    path = GOLDEN_DIR / filename
    return json.loads(path.read_text())


def _search_fixture(tenant: str, query: str, limit: int = 10) -> list[dict]:
    """Run BM25 search against fixture segment with features off (matching Go CLI)."""
    seg_dir = FIXTURE_DIR / tenant / "__search_segments"
    store = SqliteSegmentStore(str(seg_dir))
    segment = store.latest()
    assert segment is not None, f"No segment found for {tenant}"

    engine = BM25SearchEngine(
        segment.schema,
        enable_synonyms=False,
        enable_fuzzy=False,
        enable_phrase_bonus=False,
    )
    tokens = engine.tokenize_query(query)
    ranked = engine.score(segment, tokens, limit=limit)

    results = []
    for rank, doc in enumerate(ranked, 1):
        fields = segment.get_document(doc.doc_id)
        results.append(
            {
                "url": fields.get("url", doc.doc_id) if fields else doc.doc_id,
                "title": fields.get("title", "") if fields else "",
                "rank": rank,
            }
        )
    segment.close()
    return results


def test_search_webapi_routing():
    golden = _load_golden("search_webapi_ci_routing.json")
    results = _search_fixture("webapi-ci", "routing")
    assert len(results) >= 1
    assert results[0]["url"] == golden["results"][0]["url"]


def test_search_webapi_security():
    golden = _load_golden("search_webapi_ci_security.json")
    results = _search_fixture("webapi-ci", "security")
    assert len(results) >= 1
    assert results[0]["url"] == golden["results"][0]["url"]


def test_search_gitdocs_themes():
    golden = _load_golden("search_gitdocs_ci_themes.json")
    results = _search_fixture("gitdocs-ci", "themes")
    assert len(results) >= 1
    assert results[0]["url"] == golden["results"][0]["url"]


def test_search_gitdocs_plugins():
    golden = _load_golden("search_gitdocs_ci_plugins.json")
    results = _search_fixture("gitdocs-ci", "plugins")
    assert len(results) >= 1
    assert results[0]["url"] == golden["results"][0]["url"]


def test_search_localdocs_tools():
    golden = _load_golden("search_localdocs_ci_tools.json")
    results = _search_fixture("localdocs-ci", "tools")
    assert len(results) >= 1
    assert results[0]["url"] == golden["results"][0]["url"]


def test_all_golden_files_have_results():
    """Every golden file must contain at least one result."""
    for path in sorted(GOLDEN_DIR.glob("search_*.json")):
        data = json.loads(path.read_text())
        assert len(data["results"]) >= 1, f"No results in {path.name}"
